### ISSUE TITLE
Help to place images

### ISSUE THREAD

**Issue by anaraquelmendes** [anaraquelmendes/header-icons#1]
Hi Thomas, 
Can you show me the way to place the grain images correctly?
Thanks, 
Ana. 

@thomasjbradley

**Comment by thomasjbradley** [comment]
Remove the `/` from the start, from before `images`:
https://github.com/anaraquelmendes/header-icons/blob/gh-pages/index.html#L13-L14

Should be `src="images/…"`

**Comment by anaraquelmendes** [comment]
Can I place those images using flexbox?

**Comment by anaraquelmendes** [comment]
Can I place those images using flexbox?
@thomasjbradley

**Comment by thomasjbradley** [comment]
Yep, that’s the way to do it.

**Comment by anaraquelmendes** [comment]
I did it. Thanks!

@thomasjbradley
